# Use root/example as user/password credentials
version: '3.1'

services:

  mongoDB:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: G4t0_1000
    


